name: Publish NuGet.org

on:
  push:
    branches: 
    - master
    paths-ignore: 
    - '.github/workflows/**'
    - '**.md'
    - '**.docx'
    - '**.bat'
    - '**.vssettings'
  workflow_dispatch: # ручной запуск сценария

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          
      - name: Cache NuGet  
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Building
        run: |
          dotnet build MathCore -c Release
          dotnet build Tests/MathCore.Tests -c Release

      - name: Test
        run: dotnet test Tests/MathCore.Tests -c Release --no-build

      - name: Packing
        run: dotnet pack MathCore -c Release --no-build -v q -o ${{ github.workspace }}/ReleasePack --include-symbols
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Release
          path: ${{ github.workspace }}/ReleasePack
          retention-days: 1
        
  nuget:
    name: NuGet
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v7
        id: download
        with:
            name: Release
            path: ${{ github.workspace }}/ReleasePack
            
      - name: Upload to NuGet
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetApiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json
        
  github:
    name: GitHub
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v7
        id: download
        with:
            name: Release
            path: ${{ github.workspace }}/ReleasePack
            
      - name: Upload to GitHub
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/Infarh/index.json -k ${{secrets.GITHUB_TOKEN}}
        
  clean:
    name: Clean artifact
    needs: [nuget, github]
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete artefact
        uses: geekyeggo/delete-artifact@v5
        with:
            name: Release
