  
name: Publish GitHub.com/packages

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    name: Update package
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        
      - name: Building
        run: |
          dotnet build MathCore/MathCore.csproj --nologo
          dotnet build Tests/MathCore.Tests/MathCore.Tests.csproj --nologo
        
      - name: Testing
        run: dotnet test Tests/MathCore.Tests/MathCore.Tests.csproj --nologo
        
      - name: Packing
        run: dotnet pack MathCore/MathCore.csproj -c Release -v m          
      
      - name: Add Source
        run: dotnet nuget add source https://nuget.pkg.github.com/Infarh/index.json -n github -u Infarh -p ${{secrets.GITHUB_TOKEN}} 
            
      - name: Push package
        run: dotnet nuget push MathCore/bin/Release/*.nupkg --skip-duplicate -s https://nuget.pkg.github.com/Infarh/index.json -k ${{secrets.GITHUB_TOKEN}}
